log:
  level: debug
  disable_sentry: true

db:
  url: postgres://airdrop:airdrop@localhost:5432/airdrop?sslmode=disable

listener:
  addr: localhost:8000

broadcaster:
  airdrop_amount: 100stake
  cosmos_rpc: rpc_url
  chain_id: chain_id
  sender_private_key: priv_key
  query_limit: 10

verifier:
  verification_key_path: "./verification_key.json"
  allowed_age: 18
  allowed_citizenships: ["UKR"]
# during proof verification allowed_credentials_count OR allowed_credential_timestamp will be checked in public signals
# allowed_credentials_count - amount of credentials that user may create if the credentials timestamp after airdrop starting
# allowed_credential_timestamp - timestamp that limits when user might create credentials if it has more than 1
  allowed_credentials_count: 1
  allowed_credential_timestamp: 1715698750

root_verifier:
  rpc: evm_rpc_url
  contract: registration_contract_address
  request_timeout: 10s
