log:
  level: debug
  disable_sentry: true

db:
  url: postgres://airdrop:airdrop@localhost:5432/airdrop?sslmode=disable

listener:
  addr: localhost:8000

broadcaster:
  addr: broadcaster
  sender_account: "rarimo15hcd6tv7pe8hk2re7hu0zg0aphqdm2dtjrs0ds"

verifier:
  verification_keys_paths:
    sha1: "./verification_key.json"
    sha256: "./verification_key.json"
  allowed_age: 18
  allowed_citizenships: ["UKR"]

airdrop:
  amount: 100000 # urmo
