log:
  level: debug
  disable_sentry: true

db:
  url: postgres://airdrop:airdrop@localhost:5432/airdrop?sslmode=disable

listener:
  addr: localhost:8000

broadcaster:
  airdrop_amount: 100urmo
  cosmos_rpc: rpc_url
  chain_id: chain_id
  sender_private_key: priv_key
  query_limit: 10

verifier:
  verification_keys_paths:
    sha1: "./verification_key.json"
    sha256: "./verification_key.json"
  allowed_age: 18
  allowed_citizenships: ["UKR"]
